name: Build and Push to Docker Hub

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build image
        run: |
          IMAGE="${{ secrets.DOCKER_USERNAME }}/is436:${{ github.run_number }}"
          docker build -t "$IMAGE" .

      - name: Push image
        run: |
          IMAGE="${{ secrets.DOCKER_USERNAME }}/is436:${{ github.run_number }}"
          docker push "$IMAGE"
